### ISSUE TITLE
[Request] Loading tiles/blocks by specifying the row, column tile location

### ISSUE THREAD

**Issue by tblattner** [zeiss-microscopy/libCZI#3]
Request:
Add function(s) to efficiently load a row, column tile/block at a specified zoom/pyramid level. In addition, code to get the tile/block size at a specified zoom/pyramid level, and the number of tiles/blocks along the row/column dimensions.

I am working on a project that will be traversing the entire image applying various filters and machine learning models on each block of data. After peaking through the code and documentation, I noticed two primary methods for getting at the data. 
(1) 
`reader->ReadSubBlock(int blockIndex)`

(2) Using regions of interest.

Both of these methods makes a call to `reader->EnumerateSubBlocks` to traverse the sub-blocks (including all pyramid levels) of the image. The region of interest function makes a call to reader->EnumerateSubBlocks for each ROI that is requested(!).

Ideally, I would like the have the following functions:

`reader->getNumSubBlocksRow(int pyramidLevel)`
`reader->getNumSubBlocksCol(int pyramidLevel)`
`reader->getSubBlockDim(int pyramidLevel)`
`reader->getSubBlock(int row, int col, int pyramidLevel)`

getNumSubBlocksRow and getNumSubBlocksCol would return the number of sub-blocks along the row or column dimension for a specified pyramid level, respectively.

getSubBlockDim would return the sub-block's dimensions at the specified pyramid level

getSubBlock would return a std::shared_ptr<ISubBlock> at the specified row, column, and pyramid level, within bounds of getNumSubBlocksRow and getNumSubBlocksCol.

To traverse the entire image I would then do the following:

      for (int row = 0; row < reader->getNumBlocksRow(PYRAMID_LEVEL); row++)
      {
        for (int col = 0; col < reader->getNumBlocksCol(PYRAMID_LEVEL; col++)
        {

           auto subBlock = reader->getSubBlock(row, col, pyramidLevel);

           ... do processing

        }
    }

**Comment by ptahmose** [comment]
Thanks for your suggestion!
It is true that in current version a complete traversal of all sub-blocks takes place in order to determine the ones required (for composing the multi-channel- or multi-tile-composite). However - you need to be aware of the fact that sub-blocks are not required to be positioned in a checker-board arrangement. Sub-blocks may be positioned on arbitrary x-y-positions, so "row/col" would imho be an ill-defined coordinate (or: it would only be well-defined for some special cases). So, when talking about the "raw sub-block" access, row and column (and, similar argument applies to "pyramidLevel" btw.) are not well-defined and backed by the file-format. Having said that - row/column are for sure useful concepts when dealing with tile-/channel-composites - and I'd think that those concepts can be used fruitfully "on top" of the libCZI-library easily.
Regarding the performance-issue I mentioned at the outset - I'd think that we would need some indices for fast and direct access of certain subsets (e.g. specific C-coordinate, Z-coordinate, ...) and for the ROI we would need a spatial index (https://en.wikipedia.org/wiki/R*_tree, https://libspatialindex.github.io/ ). However - I would not expect this look-up to be the (largest) bottleneck in your application. Granted, I might be wrong here, in which case I would love to know more about your use-case.

**Comment by tblattner** [comment]
I was not aware that sub-blocks could be positioned in arbitrary x-y-positions! I always considered the CZI file to be generated from a Zeiss scan that traverses a slide, acquiring overlapping images. Is it more common to have arbitrary x-y positions + multi-channel? In our group we analyze 2D single channel slides.

Providing a spatial data structure, such as the R* tree that you presented, to access these sub-blocks within software would simplify access for pyramid visualization or determining ROI access. By specifying the zoom level, if the operations applied on a tile do not require the lowest zoom level, then a sub-sampled image could be processed. These are two use-cases that we are looking at to use with row-column access + zoom/pyramid level. If these were integrated into the libCZI software, then a tile/channel-composite parameter would probably have to be included as well. Currently our use case only requires single channel and no Z-coordinate.

In the meantime, internally we are investigating a simple 2D data structure to cache block locations. General idea is to use the data structure to store the CZI block index that maps to the row/column + zoom factor. Then using the CZIReader call ReadSubBlock.  The data structure will be built with a single pass through all sub blocks using the EnumerateSubBlocks routine. Eventually we might incorporate the R* or axis-aligned bounding box tree.

**Comment by ptahmose** [comment]
>Is it more common to have arbitrary x-y positions + multi-channel? In our group 
>we analyze 2D single channel slides.

Well, the file-format allows this, and there is no other way of finding out whether the sub-blocks are actually aligned in a checker-board-manner than checking the coordinates (of all sub-blocks), at least as far as I know. If e. g. Stitching was active during the acquisition, then the coordinates will be juggled around. So, it depends on how the document was created - wouldn't call this "common".

Regarding this index (spatial and/or non-spatial) for accessing sub-block: I would guess that the time spent for checking all subblocks (for a specific access) is negligible compared to the amount of time required for I/O and/or composition. If this is not the case in your use-case, I'd love to know more about it (e.g. how many sub-blocks we are talking about, and have you explored approaches in order to decouple the I/O from the subset-calculation?).

**Comment by tblattner** [comment]
The full image at this time at 10x magnification is around 72k x 37k pixels, and around 50 x 34 tiles at 1600 x 1200 pixels per tile.

We are planning on using a 20x lens, so I am expecting each dimension to double. In either case, we have finished implementing a simple vector data structure to load the header file information from libCZI so that we can request a specific row/column block. 

My main concern is compatibility with the future of the CZI file format. We were unable to locate a version number associated with the file. Ideally, we would like to get the version number and hard code it as the version that our parser supports, this way if the CZI file format were to change, we can gracefully produce a warning/error message.

If you are interested, I will be happy to share our data structure with you. I just need to add some documentation and get it cleaned up.

**Comment by ptahmose** [comment]
Well, I measure a time of around 2.5ms for "EnumerateSubBlocks" with 122,720 sub-blocks. However, since this method might be called often (depending on the exact use-case of course), it is for sure advisable to consider improving this. Having said that... with 50x34=1700 tiles I'd estimate a time of around 30-40µs, which should make it a much smaller issue in your case.

There is a "version number" found in the XML-datastructure /ImageDocument/Metadata/Information/Application/Version. There is also a version-number in the file-header (cf. CziDataStructs.h / CziStructs.h line 113). However - I'd recommend that you check all your assumptions (e. g. whether the sub-blocks are aligned in a checker-board manner, that all sub-blocks have the same physical size, that specific dimensions are present/not present etc.). The version-number will not give you information about this kind of variability.
