### ISSUE TITLE
Incorrect Output in release build

### ISSUE THREAD

**Issue by pranthakur** [zeiss-microscopy/libCZI#43]
I am getting different output in debug and release build ,can you please guide me  what i am doing wrong?

`wstring filePath = L"D:\\dev\\images\\zeis\\SWTS_N_056_Liver_iADSS.czi";
auto stream = libCZI::CreateStreamFromFile(filePath.c_str());
auto cziReader = libCZI::CreateCZIReader();
cziReader->Open(stream);

auto subBlockStatistics = cziReader->GetStatistics();

libCZI::CDimCoordinate coordinate{ { DimensionIndex::C,0} };
libCZI::ISingleChannelPyramidLayerTileAccessor::Options scptaOptions; scptaOptions.Clear();
libCZI::ISingleChannelPyramidLayerTileAccessor::PyramidLayerInfo pyrLyrInfo;
pyrLyrInfo.minificationFactor = 2;
pyrLyrInfo.pyramidLayerNo = 6;

auto accessorp = cziReader->CreateSingleChannelPyramidLayerTileAccessor();
libCZI::ISingleChannelTileAccessor::Options sctaOptions; sctaOptions.Clear();

auto bb = subBlockStatistics.boundingBox;
int tilwidth = 512 * pow(2, pyrLyrInfo.pyramidLayerNo);

int numX = ceil((float)bb.w / tilwidth);
int numY = ceil((float)bb.h / tilwidth);

for (int i = 0; i < numY; i++)
{
	for (int j = 0; j < numX; j++)
	{
		int startx = bb.x + j * tilwidth;
		int starty = bb.y + i * tilwidth;
		IntRect roi{ startx,starty,tilwidth,tilwidth };		
		auto re = accessorp->Get(roi, &coordinate, pyrLyrInfo, &scptaOptions);
		std::wstring outputfilename = L"D:\\cziOut\\";
		outputfilename += std::to_wstring(pyrLyrInfo.pyramidLayerNo);
		outputfilename += L"\\";
		outputfilename += std::to_wstring(i);
		outputfilename += L"_";
		outputfilename += std::to_wstring(j);
		outputfilename += L".png";
		CSaveData save(outputfilename, SaveDataFormat::PNG);
		save.Save(re.get());
	}
}`

Debug mode output:
![debug](https://user-images.githubusercontent.com/37903704/54920324-f63d2800-4f28-11e9-8bc7-40800b11c2fa.PNG)

Release mode output:
![release](https://user-images.githubusercontent.com/37903704/54920390-21c01280-4f29-11e9-9607-a92aa1b42a4d.PNG)

**Comment by ptahmose** [comment]
I'd think that the memory of the bitmap (into which the image is put) is not cleared.  So, in areas where there is no actual pixel-data available, you get "random data". In debug-build, the memory is probably initialized (with 0xCC, for debug-purposes), in Release-build you get what happens to be there (that's why it's gray in Debug and black in Release I guess).
The issue is probably with the Options-parameter you pass into the call to "Get" -> scptaOptions. Please see documentation of this structure -> Clear puts "NaN" into "backGroundColor", and this means that the memory should not be cleared.
Please try to set a backGroundColor, something like 

scptaOptions.backGroundColor.r=scptaOptions.backGroundColor.g=scptaOptions.backGroundColor.b=0;

This should give you a black background - or try a "1" for a white background.

BTW - if you pass in a NULL (instead of an ISingleChannelPyramidLayerTileAccessor::Options-parameter), you'll get a default which also does not clear the background - probably not a really good default.

Hope this helps!

**Comment by pranthakur** [comment]
thanks setting default bkg color solves problem :)
