### ISSUE TITLE
Compression mode 1001 not supported?

### ISSUE THREAD

**Issue by toloudis** [zeiss-microscopy/libCZI#54]
We have encountered a file with compression mode 1001 which is considered invalid by libCZI:
https://github.com/AllenCellModeling/aicspylibczi/issues/81
Can you help figure out if this should be supported or is indeed some kind of error with the file?

**Comment by cgohlke** [comment]
Compression >= 1000 is documented as "System specific RAW data" in the CZI specification v1.2.2.  No further details are given. Looks like uncompressed but vertically flipped in this case.

**Comment by toloudis** [comment]
CziUtils::CompressionModeFromInt turns 1001 into "Invalid" and then libCZI::CreateBitmapFromSubBlock throws an exception and doesn't try to return the bitmap.

**Comment by zeissmicroscopy** [comment]
Hi all,

this 1001 compression refers to an special raw CZi used to write image data "really fast" to disk  when using cameras. Such an raw CZI is not supported by libCZI.

Workaround: Open the 1001 CZI in ZEN and save it again. This should work then.

**Comment by pr4deepr** [comment]
Thanks for the comment. It is working now when I resave it using Zen with:

- Save As or 
- if I use Save As with options and select 'Original' under 'compression'

However, considering that we have 200 to 500 GB datasets, it looks like we have to duplicate them again to make it readable with libCZI!

**Comment by zeissmicroscopy** [comment]
Hi @pr4deepr ,

you mean you can already view and press the "raw" CZI in ZEN blue? AFAIK such an CZI is automatically converted to normal when opening it in ZEN since this special format is only used during "save process" when streaming data from the camera.

Can you elaborate a bit on your workflow:

* you acquire a CZI and save it to disk using ZEN Black?
* you open the CZI in ZEN Black or ZEN Blue to check the data?
* you tried to read the CZI that was already opened and saved in ZEN blue using aicslibCZI --> OK?
* you tried to read the CZI that was already opened but not saved in ZEN blue using aicslibCZI --> NOK?
* you tried to read the CZI that was never opened in ZEN blue using aicslibCZI --> NOK?

**Comment by pr4deepr** [comment]
Hi
  Thanks for the reply. We use Zen Blue (v 3.4) to acquire the data from the Zeiss lattice, and have **Auto-Save** enabled. Once the experiment is complete, it is automatically saved as a .czi file. We DO NOT do any resaving after this.  

**- you open the CZI in ZEN Black or ZEN Blue to check the data?** 
Using Zen Blue, we can open and check the data fine.
**- you tried to read the CZI that was already opened and saved in ZEN blue using aicslibCZI -->**
Yes, but it DOES NOT work when we open it using aicslibCZI
**- you tried to read the CZI that was already opened but not saved in ZEN blue using aicslibCZI**
No, We use Zen Blue for acquisition and saving (auto saving)

As I mentioned, When I open the raw .czi file with Zen Blue, it opens fine. I have to use "Save As" option to save it into a czi format that aicslibCZI can recognise.

If the auto-save is the issue, is it possible to enable a convert to "normal" czi after this?  
Thanks again!

Cheers
Pradeep

**Comment by zeissmicroscopy** [comment]
Hi @pr4deepr ,

ok, I think I should have realized that earlier ...

You are talking about CZI data acquired with the Lattice Light Sheet. AFIAK ZEN blue 3.4 should not use this anymore, but apparently there still is an issue so we will check, if this has to do with the AutoSave functionality.

Is there any chance you can give me access to a small CZI file having this problematic RAW compressing from your system?

What happens is you do not use Autosave but just acquire and save normally? Does this CZI work for you? And obviously one could automate the process of re-opening and saving the CZI again (as a workaround).

Best regards, Sebi

**Comment by zeissmicroscopy** [comment]
Hi @pr4deepr ,

the problematic compression should actually not be used in ZEN blue 3.4 anymore? Are the CZIs, that do not open "older" and where acquired with earlier versions of ZEN blue (controlling your LLS)?

Sebi

**Comment by pr4deepr** [comment]
Hi
   I havent gotten a chance to check the new files yet. I have been testing this with "older" files acquired with an earlier version of ZEN blue controlling the LLS. I'll update this once I test it using recently acquired files.

Cheers
Pradeep

**Comment by pr4deepr** [comment]
Problematic czi file [download](https://wehieduau-my.sharepoint.com/:u:/g/personal/rajasekhar_p_wehi_edu_au/EaEWuvhOXbxLsRS9Nsd3Vj4BTItqsWLkr_4Zmrg5kQKS5A?e=Cm75GA)

**Comment by pr4deepr** [comment]
Hi
  Apologies for this extremely late reply. 
I finally got my hand on the new files acquired using the latest version of Zen and I can confirm that it opens without a problem using aicsimageio.
With files from older versions of Zen, I have to resave it as a czi so that it can be recognised by aicsimageio library.

Appreciate the help in this matter 

Cheers
Pradeep

**Comment by zeissmicroscopy** [comment]
Feel free to reopen the issue in case of new questions.
