### ISSUE TITLE
eigen3 build is failing

### ISSUE THREAD

**Issue by toloudis** [zeiss-microscopy/libCZI#60]
Is anyone else seeing errors like this?
This just started happening a couple of weeks ago in our automated aicspylibczi builds. I assume Eigen updated something and the version being pulled by libCZI is not pinned.  Or else github-actions changed some compiler configuration.

```
/home/runner/work/aicspylibczi/aicspylibczi/cmake-build-debug/libCZI/Src/vendor/eigen3/src/eigen_ext/Eigen/src/Core/util/Macros.h:624:2: error: This compiler appears to be too old to be supported by Eigen
#error This compiler appears to be too old to be supported by Eigen
 ^
```

**Comment by ptahmose** [comment]
Yes, I saw this as well. libCZI-build uses the latest version of eigen3, and obviously there was some change here.

recommendation would be - change line 7 of [/cmake/ExternalEIGEN3.cmake](https://github.com/zeiss-microscopy/libCZI/blob/master/cmake/ExternalEIGEN3.cmake) to

`GIT_TAG        3147391d946bb4b6c68edd901f2add6ac1f31f8c  # this is "release version 3.4.0", we pin it to that version because as of today there are problems with the Linux-build`

PR welcome
