### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by kwiechen** [zeiss-microscopy/libCZI#9]
Hello,

currently I am using openslide's python bindings to read and analyse parts of whole slide images from different vendors. Now we have got a larger number of .czi files. Do you have plans to add python bindings to libCZI?  

Best regards,

Kai

**Comment by zeissmicroscopy** [comment]
Dear Kai,

we are very much aware that there are several programming languages, especially python, that would benefit from a ‚ready to go‘ interface to libCZI. One approach discussed is to use swig (http://www.swig.org) as an ‘interface definition’ and then generate the interfaces.

At the moment C++ is the only language that can use libCZI directly. Due to other priorities there are no plans in the near future to supply python bindings to libCZI.
